/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const {
  REACT_APP_APPSYNC_GRAPHQL_ENDPOINT,
  REACT_APP_APPSYNC_API_KEY,
  REACT_APP_COGNITO_IDENTITY_POOL_ID,
  REACT_APP_USER_POOLS_ID,
  REACT_APP_USER_POOLS_WEB_CLIENT_ID,
} = process.env;

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_appsync_graphqlEndpoint: REACT_APP_APPSYNC_GRAPHQL_ENDPOINT,
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: REACT_APP_APPSYNC_API_KEY,
  aws_cognito_identity_pool_id: REACT_APP_COGNITO_IDENTITY_POOL_ID,
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: REACT_APP_USER_POOLS_ID,
  aws_user_pools_web_client_id: REACT_APP_USER_POOLS_WEB_CLIENT_ID,
  oauth: {},
};

export default awsmobile;
